name: gtk-desktop-example
base: core18
version: '0.1' 
summary: What theme am I using?
description: |
  A python gtk application that lists what theme is being used.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

plugs:
  gnome-3-28-1804:
    interface: content
    target: gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes

environment:
    XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS

#slots:
#  gtk-app-dbus-svc:
#    interface: dbus
#    bus: session
#    name: org.gtk.Demo2

apps:
  gtk-desktop-example:
    desktop: usr/share/applications/com.github.kenvandine.gtk-desktop-example.desktop 
    command: desktop-launch $SNAP/usr/bin/gtk-desktop-example
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - gsettings
      - x11
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $SNAP/usr/lib/gtk-desktop-example:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-desktop-example:$LD_LIBRARY_PATH
      GI_TYPELIB_PATH: $SNAP/usr/lib/gtk-desktop-example/girepository-1.0:$SNAP/usr/lib/girepository-1.0:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0:$SNAP/gnome-platform/usr/lib/girepository-1.0:$SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/gnome-platform/usr/lib/python3/dist-packages:$SNAP/usr/share/gtk-desktop-example

parts:
  gtk-desktop-example:
    after: [desktop-gnome-platform]
    plugin: meson
    source: .
    meson-parameters: [--prefix=/usr]
#    build-attributes:
#      - no-system-libraries
    override-build: |
      sudo apt install -y python-setuptools
      sudo -H pip3 install -I meson==0.50.0
      snapcraftctl build
#      mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
#      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
#      mkdir -p $SNAPCRAFT_PART_INSTALL/share/sounds
    stage-packages:
      - libblkid1
      - libgcc1
      - libgcrypt20
      - libgpg-error0
      - liblzma5
      - libmount1
      - libpcre3
      - libselinux1
      - libsystemd0
      - libudev1
      - libuuid1
      - zlib1g
      - libgtk2.0-0
      - liblz4-1
      - libstdc++6
#    stage:
#      - usr
#      - share/icons
#      - share/themes
    prime:
      - usr/share/gtk-desktop-example/ 
      - usr/share/applications/
      - usr/bin/gtk-desktop-example
    build-packages:
      - appstream-util
      - libgirepository1.0-dev
#      - gtk-desktop-example

  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
